### ISSUE TITLE
StarNub Plugin

### ISSUE THREAD

**Issue by Underbalanced** [blixt/py-starbound#25]
Would you be interested in porting this into a Java plugin to work in part with StarNub server tools.

StarNub integration would allow servers to use a plugin to repair worlds, add and remove objects and even render into a website or image the worlds ect.

ts3.free-universe.com and www.starnub.org

**Comment by Underbalanced** [comment]
https://github.com/StarNub/StarNubMain/issues/3

I have fully integrated python into StarNub. You are able to use all StarNub libraries, and you are also able to write Python libraries that i can import into StarNub internally behind commands and plugins.

**Comment by Underbalanced** [comment]
Forgot to close it! I took all my code and privatized it as I am are currently making my own MMO since Starbound server modding was more work then worth with a lot of ungrateful people and a company bent on single player as its importance.

**Comment by blixt** [comment]
@Underbalanced No worries – looking forward to seeing what you make! :)
