### ISSUE TITLE
SBAsset6 files intended to be case-insensitive?

### ISSUE THREAD

**Issue by apocalyptech** [blixt/py-starbound#36]
I suspect that the internal path structure in the SBAsset6 is intended to be case-insensitive.  For instance, `/tiles/materials/ironblock.material` references `ironblock.png`, but the path name actually specified by the Pak index is `ironBlock.png` (with a capital B).  An app programmatically following that chain will currently get an exception while trying to `.get()` the all-lowercase version.

I applied this on my local checkout, which seems to do fine, though I haven't actually done much testing.  I'll whip it up into a proper PR in a bit; just wanted to get this in here before I forgot:

```patch
diff --git a/starbound/sbasset6.py b/starbound/sbasset6.py
index dd3dae7..0aecf87 100644
--- a/starbound/sbasset6.py
+++ b/starbound/sbasset6.py
@@ -27,7 +27,7 @@ class SBAsset6(object):
     def get(self, path):
         if not hasattr(self, 'index'):
             self.read_index()
-        offset, length = self.index[path]
+        offset, length = self.index[path.lower()]
         self.stream.seek(offset)
         return self.stream.read(length)
 
@@ -50,6 +50,6 @@ class SBAsset6(object):
         self.stream.seek(self.index_offset)
         self.index = {}
         for i in range(self.file_count):
-            path = sbon.read_string(self.stream)
+            path = sbon.read_string(self.stream).lower()
             offset, length = struct.unpack('>QQ', self.stream.read(16))
             self.index[path] = IndexEntry(offset, length)
```

**Comment by blixt** [comment]
I think you're right, most likely the SB devs replicated the way Windows treats paths. Send over a PR for this and I'll merge it. :)

**Comment by apocalyptech** [comment]
So yeah, after a bit more testing/looking, I don't think anything more than my original patch would be required for this.  Sent in a PR, thanks!
