### ISSUE TITLE
Reading from btree during BTreeDB5.get_all_keys and World.get_all_regions_with_tiles

### ISSUE THREAD

**Issue by apocalyptech** [blixt/py-starbound#39]
So I was writing some stuff to figure out where exactly the bookmark locations are kept (seems to be a combination of some json'd data in the player file, plus the use of layers 3 and 4 in the map itself, btw) and came across an issue where I was attempting to read data from the btree while in the middle of the `get_all_keys` loop.  Since I converted that to being a generator, it was yielding results as it went, but then my subsequent reads from the table screwed up the loop processing (since it does some relative seeks inside the loop).

So the way I see it there's three options:
1) Write the loop to only do absolute `seek`s, so any data read by the user mid-loop won't screw up the processing
2) Revert the switch to `yield` so that it's no longer a generator, so it never actually returns until it's through processing.  (When I'd been doing that originally, fwiw, the processing time to loop over entire map files was basically negligible)
3) Just document that the user Shouldn't Do That while it's looping.

Without actually looking at the code, I suspect number 1 would be the best bet, though IMO 2 isn't awful either, even though we'd be using more memory than we'd need to be doing.  Mostly I just wanted to get this in here so I didn't lose track of it myself; I'll whip up a PR within a few days.

**Comment by blixt** [comment]
Ah that makes sense. My suggestion is to either:

1) Investigate how difficult it is to do absolute seeking

2) Make the generator an internal method and instead make the public API
call it wrapped in a list(...)

I agree performance in this case is a negligible concern, but I would like
to make the code a good example of code that scales well (but developer
friendliness is the #1 concern of course).

**Comment by apocalyptech** [comment]
I suspect that option 1 is probably going to be pretty easy; I think there's only the one relative `seek`, and a quick `peek` before yielding would be more than enough to get it on the right track.

**Comment by apocalyptech** [comment]
Okay, well, doing a `tell`/`seek` turns out to be slightly more complicated than I'd hoped, because `LeafReader` itself is hardcoded to only support relative `seek`s, and I didn't care to try and unravel that to support absolute seeking as well.

I just put in a PR which is probably not as clean as what you'd hope for, which *does* use a little interstitial list inside the node-reading loop.  IMO that'd be cleaner than doing a list-redirect type thing, though of course you may feel otherwise.  :)

**Comment by blixt** [comment]
Ah yes, that makes sense, because the LeafReader doesn't currently have the ability to go backwards as it's jumping from block to block...

I think your current solution is good, but eventually I should try to get a unit test for this since there is some complexity to this now.
