### ISSUE TITLE
setup.py packaging / PyPI?

### ISSUE THREAD

**Issue by apocalyptech** [blixt/py-starbound#43]
So how would you feel about wrapping up py-starbound in a "proper" `setup.py`, which would also include entry points for the CLI utilities.  Assuming that you're okay with that, how would you feel about having this available in PyPI?  I'd certainly be happy to whip up the `setup.py` and rearrange things a bit, in a PR.

One of the downsides of doing that, of course, is that running the CLI utils directly from a git checkout wouldn't be as simple as just executing a script directly.  Instead, if you did something like `git mv region.py starbound/cliregion.py`, to run from a git checkout you'd have to do: `python -m starbound.cliregion [filename]`.  Less convenient, but it'd allow for proper installation into a venv or system.

Anyway, let me know if that's something you'd be interested in!  (Mostly just asking because I'd like to get my own map viewer properly-`setup.py`'d as well.)

**Comment by blixt** [comment]
I think this is a great idea!

If you take this one, please just update the README to explain how to install the package and how to run the various commands once set up (this can be the most prominent way for people to use this library, since then non-devs have it easier).

Bonus points for still explaining how to run the scripts from a direct clone tho. :)

**Comment by apocalyptech** [comment]
Groovy, I'll get going on this in a bit as well, then.  :)

**Comment by apocalyptech** [comment]
Oh, one thing I'd mentioned above, briefly, but never really followed up on: Had you had any interest in having this on PyPI?  I'd enjoy having my map viewer thing on there, but it seems PyPI doesn't allow dependency linking - even though `setup.py`/setuptools/pip support pointing to git repos, PyPI itself won't allow it.  No worries if not, of course!

**Comment by blixt** [comment]
Absolutely! I've gone ahead and published it here now: https://pypi.org/project/py-starbound/

Thank you for all your help in getting it PyPI ready!

**Comment by apocalyptech** [comment]
No worries, and thanks to you as well!  The library's been great to work with.  I always enjoy having something that's already done the hard work for me.  :)
